/*
 * PrettyPrinter.java
 *
 * Some starter code for a task to be completed as part of
 * Assignment #1, UVic CSC 435, Summer 2026
 *
 */

/* This code assumes that the most recent version of ANTLR4 
 * is already available (as of this writing -- 2026-05-25 -- version
 * 4.13.2 from https://www.antlr.org/).  In practical terms this
 * means that the file `antlr-4.13.2-complete.jar` is in your
 * development environments CLASSPATH.
 *
 * This code *also* assumes that a class file named MakeASTVisitor
 * -- which is an implemented of CeelishBaseVisitor -- is also
 * available. (You will, of course, need to complete MakeASTVisitor
 * as part of your work for A#1.) CeelishBaseVisitor is itself
 * generated by ANTLR4 from the Ceelish.g4 file.
 *
 * The version of Java in the labs is 21, and this is the version
 * which will be used during assignment evaluation.
 *
 */

import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;
import org.antlr.v4.runtime.misc.*;
import java.io.*;
import nodes.*;

public class PrettyPrinter{

	public static void main (String[] args) throws Exception {
        String inputFile = null;
        if ( args.length > 0 ) {
            inputFile = args[0];
        }
        InputStream is = System.in;
        if ( inputFile != null ) {
            is = new FileInputStream(inputFile);
        }

        CharStream input = CharStreams.fromStream(is);
        CeelishLexer lexer = new CeelishLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        CeelishParser parser = new CeelishParser(tokens);

        parser.setBuildParseTree(true);
        ParseTree tree = parser.program();
        MakeASTVisitor build = new MakeASTVisitor();
        ASTNode ast = build.visit(tree);
        ast.print(0);
    }
}
